CREATE DATABASE CRUD;
USE CRUD;
CREATE TABLE PEOPLE (
PEOID INT (6) UNSIGNED AUTO_INCREMENT,
PEONAME VARCHAR (50) NOT NULL,
PEOCITY VARCHAR (30) NOT NULL,
PEOPHONE VARCHAR (15),
PRIMARY KEY (PEOID)
);
SHOW TABLES;